using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using Microsoft.Win32;
namespace WinOCP;
public partial class AutomationWindow : Window {
    readonly AutomationClient client;
    readonly Action<TransferItem> add;
    readonly CancellationTokenSource lifetime=new();
    readonly ObservableCollection<AutomationRuntime> jobs=new();
    readonly string settings=Path.Combine(AppContext.BaseDirectory,"automation.json");
    readonly string history=Path.Combine(AppContext.BaseDirectory,"automation-history.json");
    AutomationRuntime? current;
    ICollectionView? jobsView,transferView,logView;
    bool loading;
    string cluster="";
    readonly AutomationJob defaults;
    public bool IsRunning=>jobs.Any(x=>x.Running);
    public AutomationWindow(AutomationClient client,Action<TransferItem> add,string source,string project,string pod,string container,string destination){
        this.client=client;this.add=add;defaults=new(){Source=source,Project=project,Pod=pod,Container=container,Destination=destination};InitializeComponent();ParallelFiles.ItemsSource=Enumerable.Range(1,16);Stability.ItemsSource=new[]{1,5,10,20,30,60,120,300};
        foreach(var job in AutomationStore.Load(settings)){if(!Guid.TryParse(job.Id,out var id))job.Id=Guid.NewGuid().ToString("N");else job.Id=id.ToString("N");if(jobs.Any(x=>x.Job.Id==job.Id))job.Id=Guid.NewGuid().ToString("N");jobs.Add(new(){Job=job});}if(jobs.Count==0)jobs.Add(new(){Job=defaults});
        foreach(var snapshot in AutomationStore.History(history).Where(x=>x.Created>=DateTime.Now.AddDays(-7))){var job=jobs.FirstOrDefault(x=>x.Job.Id==snapshot.JobId);if(job!=null)job.Transfers.Add(TransferItem.Restore(snapshot.Name,snapshot.Source,snapshot.Total,snapshot.Bytes,snapshot.State is "Queued" or "Transferring"?"Cancelled":snapshot.State,snapshot.Created,snapshot.Started,snapshot.Completed??snapshot.Created));}
        try{if(File.Exists(settings)){AutomationStore.Save(settings,jobs.Select(x=>x.Job));var legacy=Path.Combine(AppContext.BaseDirectory,"automation-receipts.json");if(jobs.Count==1&&File.Exists(legacy)&&!File.Exists(ReceiptPath(jobs[0])))File.Copy(legacy,ReceiptPath(jobs[0]));}}catch{}
        jobsView=CollectionViewSource.GetDefaultView(jobs);jobsView.Filter=value=>value is AutomationRuntime job && (job.Name+" "+job.Job.Description+" "+job.Summary).Contains(JobSearch.Text,StringComparison.OrdinalIgnoreCase);JobsList.ItemsSource=jobsView;
        loading=true;JobsList.SelectedIndex=0;current=jobs[0];Fill(current);loading=false;BindTransfers();UpdateControls();
        Loaded+=async(_,_)=>{try{cluster=(await client.Query(lifetime.Token,"config","view","--minify","-o","jsonpath={.clusters[0].cluster.server}")).Trim();if(string.IsNullOrWhiteSpace(cluster))throw new IOException("Could not identify the connected cluster.");ClusterLabel.Text=cluster;await client.Query(lifetime.Token,"whoami");loading=true;Namespaces.ItemsSource=ProjectCatalog.UserProjects(await client.Query(lifetime.Token,"get","projects","-o","json"));Namespaces.SelectedItem=Namespaces.Items.Contains(current!.Job.Project)?current.Job.Project:null;loading=false;await LoadPods(current.Job.Pod,current.Job.Container);JobStatus.Text="Select a job, save its settings, then Start.";}catch(Exception ex){Warn(ex);}};
        Closing+=(_,e)=>{if(IsRunning){e.Cancel=true;JobStatus.Text="Stop all running or paused jobs before closing.";}else{try{SaveHistory();}catch{}lifetime.Cancel();}};Closed+=(_,_)=>lifetime.Dispose();
    }
    void Fill(AutomationRuntime runtime){var job=runtime.Job;JobName.Text=job.Name;SourcePath.Text=job.Source;Pattern.Text=job.Pattern;Recursive.IsChecked=job.Recursive;ParallelFiles.SelectedItem=Math.Clamp(job.Parallel,1,16);Stability.SelectedItem=job.StableSeconds;if(Stability.SelectedIndex<0)Stability.SelectedItem=10;Destination.Text=job.Destination;Description.Text=job.Description;Namespaces.SelectedItem=Namespaces.Items.Contains(job.Project)?job.Project:null;JobPods.ItemsSource=new[]{job.Pod}.Where(x=>x.Length>0).ToArray();JobPods.SelectedItem=job.Pod;JobContainers.ItemsSource=new[]{job.Container}.Where(x=>x.Length>0).ToArray();JobContainers.SelectedItem=job.Container;}
    AutomationJob Read()=>new(){Id=current!.Job.Id,Name=JobName.Text.Trim(),Source=string.IsNullOrWhiteSpace(SourcePath.Text)?"":Path.GetFullPath(SourcePath.Text),Pattern=Pattern.Text,Project=Namespaces.SelectedItem as string??current.Job.Project,Pod=JobPods.SelectedItem as string??"",Container=JobContainers.SelectedItem as string??"",Destination=Destination.Text.Trim(),Parallel=(int?)ParallelFiles.SelectedItem??1,StableSeconds=(int?)Stability.SelectedItem??10,Recursive=Recursive.IsChecked==true,Cluster=cluster,Description=Description.Text};
    void Capture(){if(current!=null&&!current.Running&&!loading){current.Job=Read();current.Changed();}}
    async void SelectJob(object s,SelectionChangedEventArgs e){if(loading||JobsList.SelectedItem is not AutomationRuntime selected)return;try{Capture();current=selected;loading=true;Fill(selected);loading=false;BindTransfers();UpdateControls();JobStatus.Text=selected.Logs.LastOrDefault()?.Message??"Ready.";if(cluster.Length>0)await LoadPods(selected.Job.Pod,selected.Job.Container);}catch(Exception ex){Warn(ex);}}
    void NewJob(object s,RoutedEventArgs e){try{Capture();var job=new AutomationRuntime{Job=new(){Name="New upload job",Source=defaults.Source,Project=defaults.Project,Pod=defaults.Pod,Container=defaults.Container,Destination=defaults.Destination,Cluster=cluster}};jobs.Add(job);JobSearch.Clear();JobsList.SelectedItem=job;JobCount.Text=$"Total jobs: {jobs.Count}";}catch(Exception ex){Warn(ex);}}
    void SearchJobs(object s,TextChangedEventArgs e)=>jobsView?.Refresh();
    void Warn(Exception ex){loading=false;JobStatus.Text="Check the remote connection and job settings. "+ex.Message;}
    async Task LoadPods(string preferred="",string container=""){
        if(Namespaces.SelectedItem is not string project)return;var selected=current;loading=true;JobsList.IsEnabled=Namespaces.IsEnabled=JobPods.IsEnabled=JobContainers.IsEnabled=false;
        try{using var doc=JsonDocument.Parse(await client.Query(lifetime.Token,"get","pods","-n",project,"-o","json"));if(current!=selected)return;JobPods.ItemsSource=doc.RootElement.GetProperty("items").EnumerateArray().Where(x=>x.GetProperty("status").GetProperty("phase").GetString()=="Running").Select(x=>x.GetProperty("metadata").GetProperty("name").GetString()!).Order().ToArray();JobPods.SelectedItem=JobPods.Items.Contains(preferred)?preferred:null;JobContainers.ItemsSource=null;}finally{loading=false;JobsList.IsEnabled=Namespaces.IsEnabled=JobPods.IsEnabled=JobContainers.IsEnabled=true;UpdateControls();}await LoadContainers(container);
    }
    async Task LoadContainers(string preferred=""){
        if(Namespaces.SelectedItem is not string project||JobPods.SelectedItem is not string pod)return;var selected=current;using var doc=JsonDocument.Parse(await client.Query(lifetime.Token,"get","pod",pod,"-n",project,"-o","json"));if(current!=selected||JobPods.SelectedItem as string!=pod)return;JobContainers.ItemsSource=doc.RootElement.GetProperty("spec").GetProperty("containers").EnumerateArray().Select(x=>x.GetProperty("name").GetString()!).ToArray();JobContainers.SelectedItem=JobContainers.Items.Contains(preferred)?preferred:null;if(JobContainers.SelectedIndex<0)JobContainers.SelectedIndex=0;
    }
    async void NamespaceChanged(object s,SelectionChangedEventArgs e){if(loading)return;try{await LoadPods();}catch(Exception ex){Warn(ex);}}
    async void JobPodChanged(object s,SelectionChangedEventArgs e){if(loading)return;try{await LoadContainers();}catch(Exception ex){Warn(ex);}}
    void Browse(object s,RoutedEventArgs e){var picker=new OpenFolderDialog{Title="Choose source directory",InitialDirectory=SourcePath.Text};if(picker.ShowDialog(this)==true)SourcePath.Text=picker.FolderName;}
    void SaveJob(object s,RoutedEventArgs e){try{Capture();if(current==null)return;if(string.IsNullOrWhiteSpace(current.Name))throw new IOException("Enter an automation name.");FolderUploadRunner.Validate(current.Job);AutomationStore.Save(settings,jobs.Select(x=>x.Job));jobsView?.Refresh();Log(current,"INFO","Job saved.");}catch(Exception ex){Warn(ex);}}
    void DeleteJob(object s,RoutedEventArgs e){if(current==null||current.Running)return;if(!ConfirmDialog.Ask(this,"Delete job","Delete this job and its transfer history? Source and destination files are kept.","Delete"))return;try{var removed=current;jobs.Remove(removed);current=null;AutomationStore.Save(settings,jobs.Select(x=>x.Job));SaveHistory();if(jobs.Count==0)NewJob(s,e);else JobsList.SelectedIndex=0;}catch(Exception ex){Warn(ex);}}
    void UpdateControls(){if(current==null)return;var running=current.Running;SettingsPanel.IsEnabled=SaveButton.IsEnabled=DeleteButton.IsEnabled=TestButton.IsEnabled=StartButton.IsEnabled=!running;PauseButton.IsEnabled=running&&current.State!="Stopping";StopButton.IsEnabled=running;PauseButton.Content=current.State=="Paused"?"Resume":"Pause";RuntimeState.Text=current.State;JobCount.Text=$"Total jobs: {jobs.Count}";TransferHeading.Text=$"{current.Name} · {current.State}\n{current.Job.Pattern} → {current.Job.Project}/{current.Job.Pod}/{current.Job.Container} · {current.Job.Destination}";}
    void Log(AutomationRuntime job,string level,string text){job.Logs.Add(new(DateTime.Now,level,text));while(job.Logs.Count>1000)job.Logs.RemoveAt(0);if(job==current)JobStatus.Text=text;}
    string ReceiptPath(AutomationRuntime job)=>Path.Combine(AppContext.BaseDirectory,"automation-receipts-"+job.Job.Id+".json");
    FolderUploadRunner Runner(AutomationRuntime job)=>new(job.Job,client,text=>Log(job,text.StartsWith("Retry")?"WARN":text.Contains("Cancelled")?"WARN":text.Contains("Failed")?"ERROR":"INFO",text),row=>AddTransfer(job,row),ReceiptPath(job));
    void AddTransfer(AutomationRuntime job,TransferItem row){job.Transfers.Add(row);add(row);row.PropertyChanged+=(_,e)=>{if(e.PropertyName!=nameof(TransferItem.State))return;Log(job,row.State=="Failed"?"ERROR":"INFO",row.Name+" · "+row.State);if(job==current){transferView?.Refresh();UpdateCounts();}try{SaveHistory();}catch(Exception ex){Log(job,"WARN","Could not persist history: "+ex.Message);}};if(job==current)UpdateCounts();}
    void SaveHistory()=>AutomationStore.SaveHistory(history,jobs);
    async void Test(object s,RoutedEventArgs e){if(current==null)return;var selected=current;try{Capture();TestButton.IsEnabled=false;await Runner(selected).Test(lifetime.Token);Log(selected,"INFO","Configuration valid: connected and destination writable.");}catch(Exception ex){Warn(ex);}finally{UpdateControls();}}
    async void StartJob(object s,RoutedEventArgs e){if(current==null)return;try{Capture();await StartRuntime(current,true);}catch(Exception ex){Warn(ex);}}
    async Task StartRuntime(AutomationRuntime job,bool confirm){if(job.Running)return;FolderUploadRunner.Validate(job.Job);if(cluster.Length==0)throw new IOException("Connect to the remote cluster first.");if(confirm&&!ConfirmDialog.Ask(this,"Start job",$"Start {job.Name}?\n{job.Job.Source} → {job.Job.Project}/{job.Job.Pod}:{job.Job.Destination}\n\nExisting destination files may be overwritten.","Start"))return;
        job.Job.Cluster=cluster;AutomationStore.Save(settings,jobs.Select(x=>x.Job));job.Stop=CancellationTokenSource.CreateLinkedTokenSource(lifetime.Token);job.Runner=Runner(job);job.State="Running";if(job==current)UpdateControls();Log(job,"INFO","Job started.");var running=RunRuntime(job);job.Task=running;await running;
    }
    async Task RunRuntime(AutomationRuntime job){try{await job.Runner!.Run(job.Stop!.Token);job.State="Stopped";}catch(OperationCanceledException)when(job.Stop?.IsCancellationRequested==true){job.State="Stopped";Log(job,"INFO","Job stopped; partial destinations may remain.");}catch(Exception ex){job.State="Error";Log(job,"ERROR","Remote connection/job unavailable: "+ex.Message);}finally{job.Stop?.Dispose();job.Stop=null;job.Runner=null;job.Changed();if(job==current)UpdateControls();try{SaveHistory();}catch(Exception ex){Log(job,"WARN",ex.Message);}}}
    void PauseJob(object s,RoutedEventArgs e){if(current?.Runner==null)return;current.Runner.Paused=!current.Runner.Paused;current.State=current.Runner.Paused?"Paused":"Running";Log(current,"INFO",current.Runner.Paused?"Paused dispatch; active uploads finish.":"Resumed dispatch.");UpdateControls();}
    void StopJob(object s,RoutedEventArgs e){if(current?.Stop==null)return;current.State="Stopping";current.Stop.Cancel();UpdateControls();}
    void CloseWindow(object s,RoutedEventArgs e)=>Close();
    public void StopForShutdown(){foreach(var job in jobs)job.Stop?.Cancel();lifetime.Cancel();}
    void BindTransfers(){if(current==null)return;transferView=CollectionViewSource.GetDefaultView(current.Transfers);transferView.Filter=MatchesTransfer;TransferTable.ItemsSource=transferView;logView=CollectionViewSource.GetDefaultView(current.Logs);logView.Filter=value=>value is AutomationLog line && (LogLevelFilter.SelectedIndex==0 || line.Level==((LogLevelFilter.SelectedItem as ComboBoxItem)?.Content as string));LogTable.ItemsSource=logView;UpdateCounts();}
    bool MatchesTransfer(object value){if(value is not TransferItem row)return false;var status=(StatusFilter.SelectedItem as ComboBoxItem)?.Content as string;var period=TimeFilter.SelectedIndex==1?7:1;if(row.Created<DateTime.Now.AddDays(-period))return false;if(!(row.Name+" "+row.SourcePath).Contains(FileSearch.Text,StringComparison.OrdinalIgnoreCase))return false;return status switch{"Active"=>row.State=="Transferring","Queued"=>row.State=="Queued","Completed"=>row.State=="Completed","Failed"=>row.State=="Failed","Cancelled"=>row.State=="Cancelled",_=>true};}
    void UpdateCounts(){if(current==null)return;var rows=current.Transfers;ActiveCount.Text=$"{rows.Count(x=>x.State=="Transferring")}\nActive";QueuedCount.Text=$"{rows.Count(x=>x.State=="Queued")}\nQueued";CompletedCount.Text=$"{rows.Count(x=>x.State=="Completed"&&x.Completed>=DateTime.Now.AddDays(-1))}\nCompleted (24h)";FailedCount.Text=$"{rows.Count(x=>x.State=="Failed"&&x.Completed>=DateTime.Now.AddDays(-1))}\nFailed (24h)";TotalCount.Text=$"{rows.Count(x=>x.Created>=DateTime.Now.AddDays(-7))}\nTotal (7 days)";}
    void TransferFiltersChanged(object s,SelectionChangedEventArgs e)=>transferView?.Refresh();
    void LogLevelChanged(object s,SelectionChangedEventArgs e)=>logView?.Refresh();
    void SearchTransfers(object s,TextChangedEventArgs e)=>transferView?.Refresh();
    void ClearHistory(object s,RoutedEventArgs e){if(current==null)return;foreach(var row in current.Transfers.Where(x=>x.State is "Completed" or "Cancelled").ToArray())current.Transfers.Remove(row);try{SaveHistory();}catch(Exception ex){Warn(ex);}UpdateCounts();}
    void CancelTransfer(object s,RoutedEventArgs e){if(((s as FrameworkElement)?.DataContext??TransferTable.SelectedItem) is TransferItem row&&row.CanCancel)row.Cancellation.Cancel();}
    async void RetryTransfer(object s,RoutedEventArgs e){if(current==null||((s as FrameworkElement)?.DataContext??TransferTable.SelectedItem) is not TransferItem row||row.State is not ("Failed" or "Cancelled"))return;try{if(current.Runner!=null){current.Runner.Retry(row.SourcePath);Log(current,"INFO","Retry requested: "+row.Name);}else await StartRuntime(current,true);}catch(Exception ex){Warn(ex);}}
    void TransferSelected(object s,SelectionChangedEventArgs e){if(TransferTable.SelectedItem is TransferItem row)TransferDetails.Text=$"File: {row.Name}\nSource: {row.SourcePath}\nStatus: {row.State}\n{row.ProgressText}\nSpeed: {row.Speed}\nStarted: {row.Started}\nCompleted: {row.Completed}";}
    void OpenFolder(object s,RoutedEventArgs e){if(current==null)return;try{Process.Start(new ProcessStartInfo(current.Job.Source){UseShellExecute=true});}catch(Exception ex){Warn(ex);}}
}
