<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Resource Include="Assets/WinOCP-banner.png"/><Resource Include="Assets/WinOCP-emblem.png"/></ItemGroup></Project>
